version: "3.8"

services:
    rtsp-server:
        image: aler9/rtsp-simple-server
        container_name: rtsp-server
        ports:
            - "8554:8554"

    video-streamer:
        build: .
        depends_on:
            - rtsp-server
        volumes:
            - .:/app
        working_dir: /app
        command: ["node", "index.js"]
